security:
  user:
    password: 12345678
    role: READER, WRITER
server:
  port: 8081
  context-path: /authserver
logging:
  level:
    org.springframework.security: DEBUG
client:
  url: http://localhost:8080